export const GET_ERRORS = 'GET_ERRORS';
export const AUTH_USER = 'AUTH_USER';
export const SET_PROFILE_TYPE = 'SET_PROFILE_TYPE';

export const SET_CURRENT_PROFILE = 'SET_CURRENT_PROFILE';

export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';

export const GET_PROFILES = 'GET_PROFILES';
export const LOGOUT_USER = 'LOGOUT_USER';
